# Introdution to TensorFlow
* This notebook serves as a playground to get our hands dirty with TensorFlow and its API. 

## Import Libraries

In [21]:
import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

## Validate Installation

In [22]:
## printing tf version
tf.__version__

'2.19.0'

In [23]:
## check for CPU devices
cpu_devices = tf.config.list_logical_devices(device_type="CPU")
cpu_devices

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [24]:
## check for GPU devices
gpu_devices = tf.config.list_logical_devices(device_type="GPU")
gpu_devices

[]

## Hello World TF Edition

In [25]:
message = tf.constant("Hello World")
message.dtype


tf.string

In [17]:
print(message.numpy())

b'Hello World'


In [19]:
message.shape

TensorShape([])

## Tensors

### Scalar (Rank 0)

In [48]:
# A single value with no axes
val = tf.constant(4)
# printing shape
print(val.shape)
print(tf.shape(val))
# printing dtype
print(val.dtype)

()
tf.Tensor([], shape=(0,), dtype=int32)
<dtype: 'int32'>


### Vector (Rank-1)

In [49]:
vector = tf.constant([1,2,3,4])
print(vector)
print(vector.shape)
print(tf.shape(vector))
print(val.dtype)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(4,)
tf.Tensor([4], shape=(1,), dtype=int32)
<dtype: 'int32'>


### Matrix (Rank-2)

In [50]:
## here we are creating a 2x3 matrix
matrix = tf.constant([[1,2,3],[3,4,5]])
print(matrix)
print(matrix.shape)
print(tf.shape(matrix))
print(val.dtype)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)
(2, 3)
tf.Tensor([2 3], shape=(2,), dtype=int32)
<dtype: 'int32'>


In [51]:
## here we are creating a 1x3 matrix
matrix = tf.constant([[1,2,3]])
print(matrix)
print(matrix.shape)
print(tf.shape(matrix))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)
tf.Tensor([1 3], shape=(2,), dtype=int32)


### Higher Rank Tensors

In [52]:
## here we are creating a 1x2x3 matrix
data = tf.constant([[[1,2,3],[3,5,5]]])
print(data)
print(data.shape)
print(tf.shape(data))

tf.Tensor(
[[[1 2 3]
  [3 5 5]]], shape=(1, 2, 3), dtype=int32)
(1, 2, 3)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [53]:
## here we are creating a 2x2x3 matrix
data = tf.constant([[[1,2,3],[3,5,5]],[[11,22,33],[33,55,55]]])
print(data)
print(data.shape)
print(tf.shape(data))

tf.Tensor(
[[[ 1  2  3]
  [ 3  5  5]]

 [[11 22 33]
  [33 55 55]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
tf.Tensor([2 2 3], shape=(3,), dtype=int32)


### Tensor Operations

#### Rank of a Tensor

In [54]:
rank_mat = tf.constant([[1,2,3],[0,0,0],[0,0,0]])
print(rank_mat.shape)
## Note: This rank doesn't represent rank of the matrix but dimensions of the tensor i.e. number of axes
## Since this is a 2 dimensional matrix rank is 2
print(tf.rank(rank_mat))

(3, 3)
tf.Tensor(2, shape=(), dtype=int32)


#### Addition

In [55]:
## lets create 2 tensors of Rank 2 and add them
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor2 = tf.constant([[11,21,31],[41,51,61]])

tensor3 = tf.add(tensor1,tensor2)
print(tensor3.shape)
print(tensor3)

(2, 3)
tf.Tensor(
[[12 23 34]
 [45 56 67]], shape=(2, 3), dtype=int32)


In [59]:
## can we add int and float in tf
tensor1 = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
tensor2 = tf.constant([[11,21,31],[41,51,61]])

print(tensor1.dtype)
print(tensor2.dtype)

"""
So it turns out we cannot add two different types of tensors, we need to cast before addition
"""
tensor3 = tf.add(tensor1,tf.cast(tensor2, dtype=tf.float32))
print(tensor3.shape)
print(tensor3.dtype)
print(tensor3)

<dtype: 'float32'>
<dtype: 'int32'>
(2, 3)
<dtype: 'float32'>
tf.Tensor(
[[12. 23. 34.]
 [45. 56. 67.]], shape=(2, 3), dtype=float32)


In [ ]:
## can we add scalar to higher ranked Tensor?
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor2 = tf.constant(10)

print(tensor1.shape)
print(tensor2.shape)

"""
We can add a scalar to tensor, it simply broadcasts the value as long as the shapes are compatible
"""
tensor3 = tf.add(tensor1,tensor2)
print(tensor3.shape)
print(tensor3.dtype)
print(tensor3)

(2, 3)
()
(2, 3)
<dtype: 'int32'>
tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)


In [72]:
## Lets check if it always broadcasts based on the shape
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor2 = tf.constant([[10],[100]])

print(tensor1.shape)
print(tensor2.shape)

"""
It always broadcasts as long as the shape is compatible
"""
tensor3 = tf.add(tensor1,tensor2)
print(tensor3.shape)
print(tensor3.dtype)
print(tensor3)

(2, 3)
(2, 1)
(2, 3)
<dtype: 'int32'>
tf.Tensor(
[[ 11  12  13]
 [104 105 106]], shape=(2, 3), dtype=int32)


#### Multiplication

In [73]:
## element wise multiplication
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor2 = tf.constant([[11,21,31],[41,51,61]])

print(tensor1.shape, tensor1.dtype)
print(tensor2.shape, tensor2.dtype)

tensor3 = tf.multiply(tensor1,tensor2)

print(tensor3.shape, tensor3.dtype)
print(tensor3)

(2, 3) <dtype: 'int32'>
(2, 3) <dtype: 'int32'>
(2, 3) <dtype: 'int32'>
tf.Tensor(
[[ 11  42  93]
 [164 255 366]], shape=(2, 3), dtype=int32)


In [74]:
## tensor scalar multiplication
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor2 = tf.constant(10)

print(tensor1.shape, tensor1.dtype)
print(tensor2.shape, tensor2.dtype)

tensor3 = tf.multiply(tensor1,tensor2)

print(tensor3.shape, tensor3.dtype)
print(tensor3)

(2, 3) <dtype: 'int32'>
() <dtype: 'int32'>
(2, 3) <dtype: 'int32'>
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [80]:
## matrix multiplication
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor2 = tf.constant([[11,21],[41,51],[10,10]])

print(tensor1.shape, tensor1.dtype)
print(tensor2.shape, tensor2.dtype)

## the shapes of the tensors should match for matrix multiplication
tensor3 = tf.matmul(tensor1,tensor2)

print(tensor3.shape, tensor3.dtype)
print(tensor3)

## another way to perform matrix multiplication
tensor4 = tensor1  @ tensor2
print(tensor4.shape, tensor4.dtype)
print(tensor4)


(2, 3) <dtype: 'int32'>
(3, 2) <dtype: 'int32'>
(2, 2) <dtype: 'int32'>
tf.Tensor(
[[123 153]
 [309 399]], shape=(2, 2), dtype=int32)
(2, 2) <dtype: 'int32'>
tf.Tensor(
[[123 153]
 [309 399]], shape=(2, 2), dtype=int32)


#### Slicing & Indexing

In [94]:
tensor1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

print(tensor1.shape)

# all elements of the first row
print(tensor1[0,:])

# first row first column
print(tensor1[0,0])

# first row first 2 column
print(tensor1[0,0:2])

# first 2 rows first 2 columns
print(tensor1[0:2,0:2])

# all elements of first column
print(tensor1[:,0])

# all elements of last column
print(tensor1[:,-1])

(3, 3)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor([1 4 7], shape=(3,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)


#### Reshaping


In [98]:
tensor1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

print(tensor1.shape)

## reshape into row vector
reshaped_row_vec = tf.reshape(tensor1,(1,-1))
print(reshaped_row_vec.shape)

## reshape into column vector
reshaped_col_vec = tf.reshape(tensor1,(-1,1))
print(reshaped_col_vec.shape)

(3, 3)
(1, 9)
(9, 1)


#### Transpose

In [100]:
tensor1 = tf.constant([[1,2,3],[4,5,6]])
print(tensor1.shape)

tensor2 = tf.transpose(tensor1)
print(tensor2.shape)
print(tensor2)

(2, 3)
(3, 2)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


#### Converting to and from Tensors

In [112]:
np_array = np.random.rand(3,3)
print(np_array.shape)
print(type(np_array))
print(np_array)

tensor1 = tf.convert_to_tensor(np_array)
print(tensor1.shape)
print(type(tensor1))
print(tensor1)

(3, 3)
<class 'numpy.ndarray'>
[[0.173 0.754 0.098]
 [0.486 0.948 0.827]
 [0.884 0.719 0.745]]
(3, 3)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[0.173 0.754 0.098]
 [0.486 0.948 0.827]
 [0.884 0.719 0.745]], shape=(3, 3), dtype=float64)


#### Ragged Tensors - TBD
#### String Tensors - TBD
#### Sparse Tensors - TBD

## Variables

In [115]:
var1 = tf.Variable([1,2,3])
print(var1.shape)
print(type(var1))

(3,)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [117]:
var1 = tf.Variable([1,2,3])

var1.assign([10,20,30])
# print(var1.shape)
# print(type(var1))

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

Interesting to note the TF has `UnreadVariable` in type if we don't read the variable after assigning. 

In [121]:
var1 = tf.Variable([1,2,3])

## adding values to variables
var1.assign_add([10,10,10])
print(var1.shape)
print(type(var1))
print(var1.read_value())

(3,)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
tf.Tensor([11 12 13], shape=(3,), dtype=int32)


In [122]:
## adding two variables
var1 = tf.Variable([1,2,3])
var2 = tf.Variable([10,20,30])

var3 = var1 + var2
print(var3)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


In [123]:
## multiplying two variables
var1 = tf.Variable([1,2,3])
var2 = tf.Variable([10,20,30])

var3 = var1 * var2
print(var3)

tf.Tensor([10 40 90], shape=(3,), dtype=int32)


In [128]:
## Indexting and slicing
var1 = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
print(var1.shape)

# print first row
print(var1[0,:])

# first two rows
print(var1[0:2,:])

# first column
print(var1[:,0])

(3, 3)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 4 7], shape=(3,), dtype=int32)


## Automatic Differentiation

* Here we are defining the function $f(x)$ as follows
$$
f(x) = x^2 + 2x - 5
$$
* The derivative of this function would be
$$
{d \over dx}f(x) = 2x + 2
$$
* So for x = 1,
$$
f(x) = f(1) = -2\\
{d \over dx}f(x) = 2x + 2 = 4
$$

In [ ]:
x = tf.Variable(1.0)


def f(x):
    return x**2 + 2*x - 5

## compute gradient of f w.r.t x
with tf.GradientTape() as tape:
    y = f(x)

g_x = tape.gradient(y,x)
print(g_x)

tf.Tensor(4.0, shape=(), dtype=float32)


## Graph Execution

In [134]:
## this decorator optimizes the function by compiling python function into optimized computation graph
@tf.function
def my_func(x):
  return tf.reduce_sum(x)

x = tf.constant([1, 2, 3])
print(my_func(x))

tf.Tensor(6, shape=(), dtype=int32)


## Building Models

* Creating a simple TF Model using the below quadratic example
$$
J(w) = w^2 -10w + 25 = (w - 5)^2
$$
* We know that the above equation is minimum at $w = 5$.
* Lets build a TF model that finds this minimum. 
    * What that means is we'll start with a random point, find the slope of this function at that point (i.e gradient) and nudge the point in the opposite direction of the slope. 
    * We'll repeate this till fix number of iterations and see if we found the minimum.


In [ ]:
# lets define the random point w
# this will be a tf.Variable cause we'll keep chaning the value in each iteration.
w = tf.Variable(initial_value=0.0, dtype=tf.float32)

# lets define the cost function, in our case its the above function
def compute_cost():
    cost = w**2 - 10*w + 25
    return cost


# lets define the optimizer algorithm and set it to Adam
# optimizers help speed up the training by smoothning the gradient descent path.
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)
# lets create a training step


def training_step():
    # step 1: compute the cost - kind of like at the end of forward prop
    """
    The tf.GradientTape context manager is crucial. 
    It "records" operations involving tf.Variables performed within its block (like the calculation of cost which depends on w). 
    """
    with tf.GradientTape() as tape:
        cost = compute_cost()

    # training variables, i.e variables that the network learns to reduce the cost
    training_variables = [w]
    # Step 2 calculate the gradient - kind of like back prop
    grads = tape.gradient(cost, training_variables)
    # step 2.1 update the variables by subtracting the gradients
    optimizer.apply_gradients(zip(grads,training_variables))
     

In [148]:
# lets train 10 times and see how the variable changes
for i in range(10):
    training_step()
    print(w.numpy())

0.09999931
0.19994053
0.2997846
0.39948922
0.49901304
0.59831345
0.69734603
0.79606664
0.89443004
0.99239093


* So we are slowly going towards 5, lets run it 1000 times

In [150]:
# lets train 10 times and see how the variable changes
for i in range(1000):
    training_step()
print(w.numpy())

5.0000005
