In [1]:
import numpy as np

In [6]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

In [8]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [12]:
total = np.sum(A, axis=0)

In [14]:
(A / total)*100

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [15]:
print(total)
print(total.reshape(1,4))

[ 59.  239.  155.4  76.9]
[[ 59.  239.  155.4  76.9]]


In [16]:
A = np.random.randn(5)

In [17]:
A.shape

(5,)

In [18]:
A = A.reshape(5,1)

In [19]:
A.shape

(5, 1)

In [20]:
A

array([[-1.31211135],
       [ 1.22845439],
       [ 2.60611085],
       [ 0.29794241],
       [ 0.67159766]])

In [21]:
A.reshape(1,5)

array([[-1.31211135,  1.22845439,  2.60611085,  0.29794241,  0.67159766]])

In [22]:
A

array([[-1.31211135],
       [ 1.22845439],
       [ 2.60611085],
       [ 0.29794241],
       [ 0.67159766]])

In [29]:
a = np.random.rand(4,3)
b = np.random.rand(3,1)
np.dot(a,b)

array([[1.15521213],
       [1.24860754],
       [0.80007253],
       [1.30433518]])

In [30]:
x=np.array([[1,2],[3,4]])
x.shape

(2, 2)

In [34]:
a = np.random.rand(3,3)
b = np.random.rand(3,1)
a * b

array([[0.66486137, 0.14641221, 0.76346208],
       [0.07609181, 0.01942382, 0.06920913],
       [0.00100778, 0.00963697, 0.01068805]])

In [35]:
np.exp?

Signature:       np.exp(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'exp'>
File:            ~/workspace/deep_learning_specialist/env/lib/python3.12/site-packages/numpy/__init__.py
Docstring:      
exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Calculate the exponential of all elements in the input array.

Parameters
----------
x : array_like
    Input values.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain it

In [36]:
np.abs?

Signature:       np.abs(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'absolute'>
File:            ~/workspace/deep_learning_specialist/env/lib/python3.12/site-packages/numpy/__init__.py
Docstring:      
absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Calculate the absolute value element-wise.

``np.abs`` is a shorthand for this function.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsew

In [37]:
np.squeeze?

Signature:       np.squeeze(a, axis=None)
Call signature:  np.squeeze(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function squeeze at 0x10a8c1260>
File:            ~/workspace/deep_learning_specialist/env/lib/python3.12/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Remove axes of length one from `a`.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Selects a subset of the entries of length one in the
    shape. If an axis is selected with shape entry greater than
    one, an error is raised.

Returns
-------
squeezed : ndarray
    The input array, but with all or a subset of the
    dimensions of length 1 removed. This is always `a` itself
    or a view into `a`. Note that if all axes are squeezed,
    the result is a 0d array and not a scalar.

Raises
------
ValueError
    If `axis` is not None, and an axis being squeezed is not of length 1

See Also
--------
expand_dims : The inverse o

In [38]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [39]:
np.dot?

Call signature:  np.dot(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function dot>
Docstring:      
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see `numpy.linalg`).

Parameters
----------
a : array_like
    Fi

In [51]:
A = np.random.rand(3,2)
A

array([[0.43651633, 0.08223644],
       [0.08583978, 0.93332536],
       [0.8363081 , 0.48365793]])

In [53]:
np.array(np.where(A < 0.5,0,1)).shape

(3, 2)